version: '3.3'
services:
    fintrack-dev:
        build:
          context: ../../
          dockerfile: ./docker/dev_frontend/Dockerfile
        env_file: 
          - ../../.dev.env 
        volumes:
            - ../../db_dev:/usr/src/app/db
            - ../../:/usr/src/app
            - /usr/src/app/frontend/node_modules
        network_mode: {YOUR_PROXY_NETWORK_HERE} 
        container_name: fintrack-dev
        expose:
            - '9028'
        image: fintrack-dev
    fintrack-go:
        build:
          context: ../../
          dockerfile: ./docker/dev_go/Dockerfile
        env_file: 
          - ../../.dev.env
        volumes:
          - ../../db_dev:/usr/src/app/db
          - ../../backend_go:/usr/src/app/backend_go
        network_mode: {YOUR_PROXY_NETWORK_HERE} 
        container_name: fintrack-go
        expose:
          - '6060'
        image: fintrack-go