version: '3.3'
services:
    fintrack:
        build:
          context: ../../
          dockerfile: ./docker/dev_frontend/Dockerfile
        env_file: 
          - ../../.dev.env 
        volumes:
            - ../../:/usr/src/app
            - /usr/src/app/frontend/node_modules
        container_name: fintrack
        ports:
            - '9028:9028'
        image: fintrack
    fintrack-go:
        build:
          context: ../../
          dockerfile: ./docker/dev_go/Dockerfile
        env_file: 
          - ../../.env
        volumes:
          - ../../db:/usr/src/app/db
          - ../../backend_go:/usr/src/app/backend_go
        container_name: fintrack-go
        ports:
          - '6060:6060'
          - '40000:40000'
        expose:
          - '6060'
        image: fintrack-go