version: '3.3'
services:
    fintrack:
        build:
          context: .
          dockerfile: ./docker/dev/Dockerfile
        env_file: 
          - '$PWD/.env' 
        volumes:
            - '${PWD}:/usr/src/app'
            - /usr/src/app/frontend/node_modules
            - /usr/src/app/backend/node_modules
        network_mode: cbb_server_docker_default
        container_name: fintrack
        ports:
            - '9222:9222'
            - '7080:7080'
        expose:
            - '9028'
        image: fintrack
        deploy:
          resources:
            limits:
              cpus: '2'
    fintrack-stage:
        build:
          context: .
          dockerfile: ./docker/staging/Dockerfile
        env_file: 
          - './.env' 
        volumes:
            - ./data.sqlite:/usr/src/app/data.sqlite
        network_mode: cbb_server_docker_default
        container_name: fintrack-stage 
        # ports:
            # - '9222:9222'
        expose:
            - '9028'
        image: fintrack-stage
        deploy:
          resources:
            limits:
              cpus: '2'