version: '3.3'
services:
    fintrack-go:
        build:
          context: .
          dockerfile: ./docker/dev_go/Dockerfile
        env_file: 
          - '$PWD/.env.prod' 
        volumes:
          - ${PWD}/db:/usr/src/app/db
          - ${PWD}/backend_go:/usr/src/app/backend_go
        network_mode: cbb_server_docker_default
        container_name: fintrack-go
        ports:
          - '6060:6060'
          - '40000:40000'
        image: fintrack-go
        deploy:
          resources:
            limits:
              cpus: '2'
