version: '3.3'
services:
    fintrack:
        build:
          context: .
          dockerfile: ./docker/staging/Dockerfile
        env_file: 
          - './.env' 
        volumes:
            - ./test.sqlite:/usr/src/app/test.sqlite
        network_mode: cbb_server_docker_default
        container_name: fintrack
        # ports:
            # - '9222:9222'
        expose:
            - '9028'
        image: fintrack
        deploy:
          resources:
            limits:
              cpus: '2'