version: '3.3'
services:
    fintrack:
        build:
          context: ../../
          dockerfile: ./docker/dev_frontend/Dockerfile
        env_file: 
          - ../../.env 
        volumes:
            - ../../:/usr/src/app
            - /usr/src/app/frontend/node_modules
        container_name: fintrack
        ports:
            - '9028:9028'
        image: fintrack