version: '3.3'
services:
    fintrack-go:
        build:
          context: ../../
          dockerfile: ./docker/dev_go/Dockerfile
        env_file: 
          - ../../.env
        volumes:
          - ../../db:/usr/src/app/db
          - ../../backend_go:/usr/src/app/backend_go
        container_name: fintrack-go
        ports:
          - '6060:6060'
          - '40000:40000'
        image: fintrack-go