version: '3.3'
services:
    fintrack-stage:
        build:
          context: ../../
          dockerfile: ./docker/staging/Dockerfile
        env_file: 
          - ../../.env 
        volumes:
          - ../../db_stage:/usr/src/app/db
        network_mode: {YOUR_PROXY_NETWORK_HERE} 
        container_name: fintrack-stage
        expose:
            - '9028'
        image: fintrack-stage